server {
    # Unique and safe entrypoint: port 443 for IPv4 e IPv6
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name vjan-nie.42.fr;

    # TLS protocols
    ssl_protocols TLSv1.2 TLSv1.3;

    # Certificate paths
    ssl_certificate     /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Server root and index files
    root /var/www/html;
    index index.php index.html index.htm;

    # 1. WordPress rule: permanent links and normal requests 
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # 2. PHP processing configuration (PHP-FPM)
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # 3. Inverse PROXY for Adminer
    # Allows access through https://vjan-nie.42.fr/adminer/
    location /adminer/ {
        proxy_pass http://adminer:8080/;
        include fastcgi_params; # Mantiene cabeceras necesarias
    }

    # 3. Inverse PROXY for Static
    # Allows access through https://vjan-nie.42.fr/static/
    location /static/ {
        proxy_pass http://static:80/;
    }
}
