version: "3.8"

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb

networks:
  inception:
    name: inception_network
    driver: bridge

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress

  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/mariadb